import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import { GiDeerTrack, GiClick } from "react-icons/gi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Slcd web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <React.Fragment>
        <div className="container">
          <div className="row justify-content-center mt-7">
            <div className="col-lg-5 text-center">
              <div className="card mt-5">
                <div className="card-body py-5 px-lg-5">
                  <div className="svg-icon svg-icon-xl text-purple">
                    <GiDeerTrack className="fs-1" />
                  </div>
                  <h3 className="fw-normal text-dark mt-4">
                    Seguimiento del progreso del archivo
                  </h3>
                  <p className="mt-4 mb-1">
                    Le enviamos un código de número de archivo a su correo electrónico.
                  </p>
                  <p>Ingrese el número de archivo en el campo a continuación.</p>
                  <div className="row mt-4 pt-2">
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-4"
                        maxLength="1"
                        autoFocus
                      />
                    </div>
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-4"
                        maxLength="1"
                      />
                    </div>
                    <div className="col">
                      <input
                        type="text"
                        className="form-control text-center py-4"
                        maxLength="1"
                      />
                    </div>
                  </div>
                  <a
                    href="#!"
                    className="btn btn-lg w-100 hover-lift-light mt-4 text-white"
                    style={{ background: "#6672e8", borderColor: "#6672e8" }}
                  >
                    Seguimiento ahora <GiClick />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </React.Fragment>
    </>
  );
}
