# Generated by Django 3.2.15 on 2023-04-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0002_rename_converted_date_file_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='correct_document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='payment_receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='payment_status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='process_act_num_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='resolution_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='updatedAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
