# Generated by Django 3.2.15 on 2023-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filed', '0003_auto_20230411_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veriydoc',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='veriydoc',
            name='observation_date',
        ),
        migrations.RemoveField(
            model_name='veriydoc',
            name='review',
        ),
        migrations.RemoveField(
            model_name='veriydoc',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='veriydoc',
            name='underReview',
        ),
        migrations.RemoveField(
            model_name='veriydoc',
            name='underReview_date',
        ),
        migrations.AddField(
            model_name='file',
            name='observation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='observation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='underReview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='underReview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
